library(yaml)
library(DPR2)
df1 <- data.frame(x = 1:11, y = LETTERS[1:11])
df2 <- data.frame(y = 1:5, y = letters[1:5])
df_list <- list(a = 'x', b = 'y', c = 'z')
yml <- as.yaml(df2)
descript <- desc::desc()
dpr_save('df1')
dpr_save('df2')
dpr_save('df_list')
dpr_save('yml')
dpr_save('descript')
