library(DPR2)
df1 <- data.frame(x = 1:11, y = LETTERS[1:11])
df2 <- data.frame(y = 1:5, y = letters[1:5])
dpr_save('df1')
correct_name_rda <- dpr_path('data', 'df1.rda')
file.copy(correct_name_rda, dpr_path('data', 'wrong_name.rda'))
unlink(correct_name_rda)
dpr_save('df2')
