---
title: "DataPackageR Compatibility"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DataPackageR Compatibility}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Converting a DPR1 Datapackage to DPR2

Sometimes users may encounter datapackages created by DataPackageR. DPR2 has the function `dpr_convert` which converts a DataPackageR package into a DPR2 package.

```{r}
# existing DataPackageR project
library(DPR2)
library(DataPackageR)
library(yaml)

# setup an empty DataPackageR skeleton
dpr1tmp <- tempdir()
file.copy(
  "../tests/testthat/dpr1package/",
  dpr1tmp,
  recursive = TRUE
)

# set working directory for this vignette to the newly created datapackage
knitr::opts_knit$set(root.dir = file.path(dpr1tmp, "dpr1package"))

# create YML
yml <- DataPackageR::construct_yml_config(code = "mtcars.Rmd", data = "mtcars_mod")

cat(yaml::as.yaml(yml))
```

After using `dpr_convert`, and looking over the yaml settings, we see the yaml configuration for the DataPackageR package is converted to DPR2 compatible settings:

```{r}
dpr_convert()
dpr_yaml_get()
```
