##' dpr_get_template function lets users locate file templates by matching file
##' names against a specified regular expression
##' @title dpr_get_template
##' @return a character vector
##' @author jmtaylor
##' @param regex a regular expression
dpr_get_template <- function(regex){
  list.files(system.file("templates", package="DPR2"), regex, full.names = TRUE)
}

##' This function returns default key:value pairs for the data package datapackager.yml.
##' @title dpr_yaml_defaults
##' @return a named list with default values for the YAML file
##' @author jmtaylor
##' @export
dpr_yaml_defaults <- function(){
  return(yaml::read_yaml(dpr_get_template("datapackager.yml$")))
}

##' Provides a set of default key:value pairs for the data package DESCRIPTION file.
##'
##' @title dpr_description_defaults
##' @return a named list with default values for the YAML file
##' @author jmtaylor
##' @export
dpr_description_defaults <- function(){
  defd <- dpr_get_template("DESCRIPTION")
  return(
    as.list(
      desc::desc_get(desc::desc_fields(defd), defd)
    )
  )
}

##' Private. A function that takes a custom description list and a file path to the package,
##' applies that to package's DESCRIPTION file
##' key:values pairs in a new data package.
##'
##' @title dpr_description_init_set
##' @param desc an R desc object of metadata values to be applied to the DESCRIPTION file
##' @param pkgp the file path of the package where DESCRIPTION file is located
##' @author jmtaylor
dpr_description_init_set <- function(desc, pkgp){
  do.call(desc::desc_set, c(desc, file = pkgp))
}


##' A private function that sets custom values and generates yaml file
##' @title dpr_yaml_init_set
##' @param yml a list of custom values to be set in the YAML file
##' @param pkgp the file path of the package where datapackager.yml file is saved
##' @author jmtaylor
dpr_yaml_init_set <- function(yml, pkgp){
  def <- dpr_yaml_defaults()
  new <- utils::modifyList(def, yml, keep.null = TRUE)
  yaml::write_yaml(new, file.path(pkgp, "datapackager.yml"))
}

##' A function where each argument correspond to a specific key and adds/overrides to the
##' datapackager.yml file's key:value pairs. If no arguments are provided, it will return the
##' datapackager.yml default values. see `dpr_yaml_defaults()` for a list of
##' default values, or call this function with no arguments.
##'
##' @title dpr_yaml_init
##' @param ... Arguments are treated as key value pairs for the
##'     datapackager.yml file.
##' @return A list of key:value pairs for generating a
##'     datapackager.yml file.
##' @author jmtaylor
##' @export
dpr_yaml_init <- function(...){
  utils::modifyList(dpr_yaml_defaults(), list(...), keep.null = TRUE)
}

##' A function for creating and customizing package descriptions, allowing users
##' to set and override default metadata elements of the package.
##' Each arguments correspond to a specific key and adds/overrides to the
##' DESCRIPTION file's key:value pairs. Uses the
##' default values set by `dpr_description_defaults()` which can be generated by
##' passing no arguments.
##'
##'
##' @title dpr_description_init
##' @param ... Arguments are treated as key value pairs for the
##'     package DESCRIPTION file.
##' @return A list of key:value pairs for generating a DESCRIPTION
##'     file.
##' @author jmtaylor
##' @export
dpr_description_init <- function(...){
  vals <- list(...)
  desc <- dpr_description_defaults()
  if(!"Package" %in% names(vals))
    warning("Default package name used: ", desc$Package)
  ## override defaults and add options with arguments
  utils::modifyList(desc, vals, keep.null = TRUE)
}


##' Initialize a data package by creating a structured directory skeleton for a new R package .
##' Sets up essential directories, initializes
##' package metadata in datapackager.yml and DESCRIPTION files as described by
##' dpr_yaml_init() and dpr_description_init() function calls.
##'
##' @title dpr_init
##' @param path A character string specifying the path where the package will be created. Default is current directory.
##' @param yaml  A configuration object created with dpr_yaml_init()
##' @param desc A description object for dpr_description_init()
##' @param renv_init A logical value indicating whether to initiate renv (default TRUE)
##' @author jmtaylor
##' @export
dpr_create <- function(path = ".", yaml = dpr_yaml_init(), desc = dpr_description_init(), renv_init = TRUE){
  pkgp <- file.path(path, desc$Package)

  if(dir.exists(pkgp))
    stop(sprintf("Package '%s' path already exists.", pkgp))
  if(!dir.exists(dirname(pkgp)))
    stop("Package directory does not exist.")

  if(!dir.exists(path))
    stop("`path` argument does not point to an existing directory.")

  tryCatch(
  {

    ## create package skeleton
    dirs <- c("data", "inst", yaml$process_directory, yaml$source_data_directory, yaml$data_digest)
    dir.create(pkgp, showWarnings = FALSE)

    for( dir in dirs )
      if(!dir.create(file.path(pkgp, dir), showWarnings = FALSE))
        warning(sprintf("`%s` was found, skipping creating that directory.", dir))

    for( fil in c("NAMESPACE", "DESCRIPTION", "datapackager.yml") )
      if(!file.copy(system.file("templates", fil, package="DPR2"), file.path(pkgp, fil)))
        warning(sprintf("`%s` was found, skipping creating that file.", fil))
      else {
        if( fil == "DESCRIPTION" )
          dpr_description_init_set(desc, pkgp)
        if( fil == "datapackager.yml" )
          dpr_yaml_init_set(yaml, pkgp)
      }

    ## init renv
    if(renv_init && !file.exists(file.path(pkgp, "renv.lock")))
      renv::init(
        pkgp,
        settings = list(snapshot.type = "implicit"),
        load = FALSE,
        restart = FALSE
      )

  },
  error = function(e){
    if(dir.exists(pkgp))
      unlink(pkgp, recursive=TRUE)
    stop(e, traceback())
  })

}

##' A wrapper for dpr_create that uses the parent directory as the
##' location to create the data package, setting the package name as
##' the current directory.
##'
##' @title dpr_init
##' @author jmtaylor
##' @param path a path value to init at a specific path, when using
##'   the default the current working directory is used.
##' @param yaml A returned list for dpr_yaml_init()
##' @param desc A returned list for dpr_description_init()
##' @param renv_init Logical; whether to initiate renv (default TRUE)

##' @export
dpr_init <- function(
    path = ".",
    yaml = dpr_yaml_init(),
    desc = dpr_description_init(),
    renv_init = TRUE)
{
  path <- normalizePath(path)
  dpr_create(
    dirname(path),
    yaml = yaml,
    desc = utils::modifyList(desc, list(Package = basename(path)), keep.null = TRUE),
    renv_init = renv_init
  )
}
