##' Provides a set of default key:value pairs for the data package datapackager.yml file.
##'
##' Definitions of yaml key:value pairs
##' @title dpr_yaml_defaults
##' @return a named list with default values for the YAML file
##' @author jmtaylor
##' @export
dpr_yaml_defaults <- function(){
  list(
    "build_output"                 = "../",
    "data_directory"               = "data",
    "source_data_directory"        = "inst/extdata",
    "install_on_build"             = FALSE,
    "build_tarball"                = FALSE,
    "process_directory"            = "processing",
    "process_on_build"             = "",
    "render_on_build"              = TRUE,
    "write_to_vignettes"           = TRUE,
    "auto_increment_data_versions" = TRUE,
    "purge_data_directory"         = TRUE,
    "data_digest_directory"        = "inst/data_digest",
    "render_env_mode"              = "isolate"
  )
}

##' Provides a set of default key:value pairs for the data package DESCRIPTION file.
##'
##' @title dpr_description_defaults
##' @return a named list with default values for the YAML file
##' @author jmtaylor
##' @export
dpr_description_defaults <- function(){
  list(
    "Package"     = "MyDataPackage",
    "Title"       = "MyDataPackageTitle",
    "Version"     = "1.0",
    "Authors"     = "FirstName LastName [aut, cre]",
    "Description" = "What the package does (one paragraph).",
    "License"     = "See `https://www.gnu.org/licenses/license-list.html` or `https://choosealicense.com/` for more information",
    "Encoding"    = "UTF-8",
    "Depends"     = "R (>= 3.5)"
  )
}

##' Private. A function that takes a custom description list and a file path to the package, applies that to
##' package's DESCRIPTION file
##' key:values pairs in a new data package.
##'
##' @title dpr_description_init_set
##' @param desc an R desc object of metadata values to be applied to the DESCRIPTION file
##' @param pkgp the file path of the package where DESCRIPTION file is located
##' @author jmtaylor
dpr_description_init_set <- function(desc, pkgp){
  defa <- dpr_description_defaults()
  invisible(
    Map(desc::desc_set_list, key = names(defa), list_value = defa, file = pkgp)
  )
  invisible(
    Map(desc::desc_set_list, key = names(desc), list_value = desc, file = pkgp)
  )
}

##' Private. A function that sets custom values and generates yaml file
##' key:values pairs in a new data package.
##'
##' @title dpr_yaml_init_set
##' @param yml a list of custom values to be set in the YAML file
##' @param pkgp the file path of the package where datapackager.yml file is saved
##' @author jmtaylor
dpr_yaml_init_set <- function(yml, pkgp){
  def <- dpr_yaml_defaults()
  new <- dpr_set_keys(def, yml)
  yaml::write_yaml(new, file.path(pkgp, "datapackager.yml"))
}

##' A function where each argument correspond to a specific key and adds/overrides to the
##' datapackager.yml file's key:value pairs. If no arguments are provided, it will return the
##' datapackager.yml default values. see `dpr_yaml_defaults()` for a list of
##' default values, or call this function with no arguments.
##'
##' @title dpr_yaml_init
##' @param ... Arguments are treated as key value pairs for the
##'     datapackager.yml file.
##' @return A list of key:value pairs for generating a
##'     datapackager.yml file.
##' @author jmtaylor
##' @export
dpr_yaml_init <- function(...){
  vals <- list(...)
  yaml <- dpr_yaml_defaults()
  ## override defaults and add options with arguments
  for(val in names(vals))
    yaml[[val]] <- vals[[val]]
  return(yaml)
}

##' A function for creating and customizing package descriptions, allowing users to set and override default metadata elements of the package.
##' Each arguments correspond to a specific key and adds/overrides to the
##' DESCRIPTION file's key:value pairs. Uses the
##' default values set by `dpr_description_defaults()` which can be generated by passing no arguments.
##'
##'
##' @title dpr_description_init
##' @param ... Arguments are treated as key value pairs for the
##'     package DESCRIPTION file.
##' @return A list of key:value pairs for generating a DESCRIPTION
##'     file.
##' @author jmtaylor
##' @export
dpr_description_init <- function(...){
  vals <- list(...)
  desc <- dpr_description_defaults()
  if(!"Package" %in% names(vals))
    warning("Default package name used: ", desc$Package)
  ## override defaults and add options with arguments
  for(val in names(vals))
    desc[val] <- vals[[val]]
  return(desc)
}

##' Initialize a data package by creating a structured directory skeleton for a new R package . Sets up essential directories, initializes
##' package metadata in datapackager.yml and DESCRIPTION files as described by
##' dpr_yaml_init() and dpr_description_init() function calls.
##'
##' @title dpr_init
##' @param path A character string specifying the path where the package will be created. Default is current directory.
##' @param yaml  A configuration object created with dpr_yaml_init()
##' @param desc A description object for dpr_description_init()
##' @param renv_init A logical value indicating whether to initiate renv (default TRUE)
##' @author jmtaylor
##' @export
dpr_init <- function(path = ".", yaml = dpr_yaml_init(), desc = dpr_description_init(), renv_init = TRUE){
  pkgp <- file.path(path, desc$Package)

  if(dir.exists(pkgp))
    stop(sprintf("Package '%s' path already exists.", pkgp))
  if(!dir.exists(dirname(pkgp)))
    stop("Package directory does not exist.")

  tryCatch(
  {

    ## create package skeleton
    dirnm <- c("data", "inst", yaml$process_directory, yaml$source_data_directory, yaml$data_digest)

    tpath <- system.file("templates", package="DPR2")

    dir.create(pkgp)
    for( dir in dirnm )
      dir.create(file.path(pkgp, dir))
    for( fil in c("NAMESPACE", "DESCRIPTION"))
      file.copy(file.path(tpath, fil), file.path(pkgp, fil))

    dpr_description_init_set(desc, pkgp)
    dpr_yaml_init_set(yaml, pkgp)

    ## init renv
    if(renv_init == TRUE)
      renv::init(
        pkgp,
        settings = list(snapshot.type = "implicit"),
        load = FALSE,
        restart = FALSE
      )

  },
  error = function(e){
    if(dir.exists(pkgp))
      unlink(pkgp, recursive=TRUE)
    stop(e, traceback())
  },
  finally = {
  })

}
